### ISSUE TITLE
Issue about tags not searching correctly

### ISSUE THREAD

**Issue by HueLiu** [BangumiMoe/rin-pr#7]
Hi guys, I'm not sure if it's appropriate to create a new issue here, so please forgive me because I can't find a corresponding feedback portal in bangumi.moe.

The issue I'm having is that I can't search for certain anime when I click on their tags directly in the Anime List (每日放送表/番组列表) . However, when I manually search for the title of the anime, it could be shown normally.

For example, if I click on [Mars Red](https://bgm.ptr.moe/bangumi/6065f093eaf504d0216b778c)  in the  Anime List (每日放送表/番组列表), nothing could be found.
![image](https://user-images.githubusercontent.com/19755727/116338985-3c9f9800-a80f-11eb-8854-f7b5e686009b.png)

If I try to search for [Mars Red](https://bgm.ptr.moe/search?query=Mars%20Red), I can get the results.
![image](https://user-images.githubusercontent.com/19755727/116338921-1bd74280-a80f-11eb-972b-a6772f2abf98.png)

The same issue could happen on both https://bangumi.moe and https://bgm.ptr.moe 

I'm not sure what the problem is, so I'd like to give you some feedback. Thanks!

**Comment by tengattack** [comment]
Tag should be added to the torrent by the uploader:

![image](https://user-images.githubusercontent.com/1846356/116366761-39210680-a839-11eb-8738-a10cc3233aad.png)

So that, we can use tag search. BTW, some search method could use title text search, so it will no need the tag in torrent.

**Comment by tengattack** [comment]
It seems NC-Raws upload their torrent by some automatic tool, if so could you tell them to use the Content Suggestion API to add tags?

**Comment by HueLiu** [comment]
> It seems NC-Raws upload their torrents by automatic tool, if so could you tell them to use the Content Suggestion API to add tags?

Ok thanks, I'll try to contact them.
I will also update this issue if there is anything new.

**Comment by HueLiu** [comment]
It seems work now. Thank you so much for your help!
